name: Pipeline 01 - Syntax Check

on:
  push:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Python Syntax Check
        run: |
          if [ -f "app.py" ]; then
              python -m py_compile app.py || exit 1
          else
              echo "No app.py found, skipping Python syntax check."
          fi

      - name: JavaScript Syntax Check
        run: |
          if [ -f "app.js" ]; then
              node -c app.js || exit 1
          else
              echo "No app.js found, skipping JS syntax check."
          fi

      - name: Java Syntax Check
        run: |
          if [ -f "App.java" ]; then
              javac App.java || exit 1
          else
              echo "No App.java found, skipping Java syntax check."
          fi

      - name: Analyse Rapport
        run: |
          python analyse_syntax.py
